export const AWS_SERVICE_NAMES: Record<string, string> = {
  ec2: 'EC2',
  console: 'AWS Console',
  eks: 'EKS',
  cloudwatch: 'CloudWatch',
  s3: 'S3',
  rds: 'RDS',
  lambda: 'Lambda',
  iam: 'IAM',
  vpc: 'VPC',
  route53: 'Route 53',
  elasticloadbalancing: 'Elastic Load Balancing',
  cloudfront: 'CloudFront',
  dynamodb: 'DynamoDB',
  sqs: 'SQS',
  sns: 'SNS',
  elasticache: 'ElastiCache',
  ecs: 'ECS',
  codedeploy: 'CodeDeploy',
  codecommit: 'CodeCommit',
  codebuild: 'CodeBuild',
  codepipeline: 'CodePipeline',
  secretsmanager: 'Secrets Manager',
  kms: 'KMS',
  apigateway: 'API Gateway',
  glue: 'Glue',
  athena: 'Athena',
  redshift: 'Redshift',
  emr: 'EMR',
  kinesis: 'Kinesis',
  stepfunctions: 'Step Functions',
  sagemaker: 'SageMaker',
  bedrock: 'Bedrock',
  multipleservices: 'Multiple Services',
};

// Always shown in the region drill-down, in this order
export const AWS_CRITICAL_SERVICE_IDS = [
  'ec2',
  'console',
  'eks',
  'cloudwatch',
  's3',
  'rds',
  'lambda',
  'iam',
  'vpc',
  'route53',
];

// Maps our canonical service IDs to the slug used in per-service RSS URLs:
// https://status.aws.amazon.com/rss/{slug}-{region}.rss
export const AWS_SERVICE_RSS_SLUGS: Record<string, string> = {
  ec2: 'ec2',
  console: 'management-console',
  eks: 'eks',
  cloudwatch: 'cloudwatch',
  s3: 's3',
  rds: 'rds',
  lambda: 'lambda',
  iam: 'iam',
  vpc: 'vpc',
  route53: 'route53',
};
